"""Regenerate self-hosted Material Symbols subsets; see docs/performance.md."""
import hashlib
import json
import subprocess
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
tokens = set(json.loads(subprocess.check_output(
    ["node", str(ROOT / "scripts/icon-source-tokens.mjs")], text=True
)))

output = ROOT / "assets/fonts"
output.mkdir(parents=True, exist_ok=True)
manifest = {"packageVersion": json.loads((ROOT / "node_modules/material-symbols/package.json").read_text())["version"], "fonts": {}}
for style in ("outlined", "rounded"):
    source = ROOT / f"node_modules/material-symbols/material-symbols-{style}.woff2"
    font = TTFont(source, recalcTimestamp=False)
    # A ligature's input spelling may be an alias for its output glyph name.
    cmap = font.getBestCmap()
    letters = {glyph: chr(code) for code, glyph in cmap.items() if code < 128}
    ligatures = []
    for lookup in font["GSUB"].table.LookupList.Lookup:
        for table in lookup.SubTable:
            table = getattr(table, "ExtSubTable", table)
            if hasattr(table, "ligatures"):
                ligatures.append(table)
    available = set()
    selected = set()
    selected_glyphs = set()
    for table in ligatures:
        for first, entries in list(table.ligatures.items()):
            kept = []
            for entry in entries:
                name = "".join(letters.get(glyph, "?") for glyph in [first, *entry.Component])
                available.add(name)
                if name in tokens:
                    kept.append(entry)
                    selected.add(name)
                    selected_glyphs.add(entry.LigGlyph)
            table.ligatures[first] = kept
    # Prune unwanted ligatures before closure, otherwise retaining the alphabet
    # would pull every icon back in. Keep all variable axes and FILL substitutions.
    options = subset.Options()
    options.flavor = "woff2"
    options.recalc_timestamp = False
    options.layout_features = ["*"]
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(glyphs=selected_glyphs, text="".join(sorted(selected)))
    subsetter.subset(font)
    target = output / f"material-symbols-{style}.woff2"
    font.save(target)
    manifest["fonts"][style] = {
        "availableIcons": sorted(available), "includedIcons": sorted(selected),
        "sourceBytes": source.stat().st_size, "subsetBytes": target.stat().st_size,
        "sha256": hashlib.sha256(target.read_bytes()).hexdigest(),
    }
    print(f"{style}: {len(selected)} icons; {source.stat().st_size:,} -> {target.stat().st_size:,} bytes")
(output / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
(output / "LICENSE").write_bytes((ROOT / "node_modules/material-symbols/LICENSE").read_bytes())
css = []
for style in ("outlined", "rounded"):
    original = (ROOT / f"node_modules/material-symbols/{style}.css").read_text()
    css.append(original)
(output / "symbols.css").write_text("/* Generated by scripts/build-icon-fonts.py. */\n" + "\n".join(css))
